subgraphs:
  rickandmorty:
    routing_url: https://rickandmortyapi.com/graphql
    schema:
      file: ../services/rickandmorty/federated-rickandmorty.graphql
  extension:
    routing_url: http://localhost:4001/graphql
    schema:
      subgraph_url: http://localhost:4001/graphql